-- Run this in the Supabase SQL Editor before configuring DATABASE_URL.
-- The FastAPI backend connects directly using its private database URL.

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  device_id varchar(100) not null unique,
  plant_name varchar(150) not null,
  plant_type varchar(100) not null default 'Herb',
  location varchar(150) not null default 'Indoor',
  moisture_threshold integer not null default 35 check (moisture_threshold between 0 and 100),
  watering_enabled boolean not null default true,
  created_at timestamp without time zone not null default timezone('utc', now())
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  device_id varchar(100) not null references public.devices(device_id) on delete cascade,
  soil_moisture double precision not null check (soil_moisture between 0 and 100),
  temperature double precision not null check (temperature between -20 and 60),
  humidity double precision not null check (humidity between 0 and 100),
  light_level double precision check (light_level between 0 and 100),
  timestamp timestamp without time zone not null default timezone('utc', now())
);

create table if not exists public.watering_events (
  id bigint generated by default as identity primary key,
  device_id varchar(100) not null references public.devices(device_id) on delete cascade,
  trigger_type varchar(50) not null,
  moisture_before double precision,
  moisture_after double precision,
  duration_seconds integer not null default 0,
  timestamp timestamp without time zone not null default timezone('utc', now())
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  device_id varchar(100) not null references public.devices(device_id) on delete cascade,
  alert_type varchar(80) not null,
  message text not null,
  status varchar(30) not null default 'open',
  created_at timestamp without time zone not null default timezone('utc', now())
);

create index if not exists ix_sensor_readings_device_time
  on public.sensor_readings (device_id, timestamp desc);
create index if not exists ix_watering_events_device_time
  on public.watering_events (device_id, timestamp desc);
create index if not exists ix_alerts_device_created
  on public.alerts (device_id, created_at desc);

-- This project accesses these tables through the backend's private Postgres
-- connection. Do not expose the database password or service credentials to
-- the browser. For direct Supabase client access, enable RLS and add user-scoped
-- policies before shipping that integration.
